name: libsecp256k1
version: 0.2.1
synopsis: Bindings for secp256k1
description: Sign and verify signatures using the secp256k1 library.
category: Crypto
author: Keagan McClelland
maintainer: keagan.mcclelland@gmail.com
copyright: (c) 2017 Jean-Pierre Rupp; (c) 2020 Haskoin Developers; (c) 2022 Keagan McClelland
license: MIT
license-file: LICENSE
github: ProofOfKeags/libsecp256k1-haskell.git
homepage: http://github.com/ProofOfKeags/secp256k1-haskell#readme
extra-source-files:
  - CHANGELOG.md
  - README.md
dependencies:
  - base >=4.9 && <5
  - bytestring >=0.10.8 && <0.12
  - deepseq >=1.4.8 && <1.5
  - entropy >= 0.3.8 && <0.5
  - hashable >=1.4.2 && <1.5
  - hedgehog >= 1.2 && <1.5
  - memory >= 0.14.15 && <1.0
  - random >=1.2.1.2 && <1.3
  - transformers >= 0.4.0.0 && <1.0
default-extensions:
  - ImportQualifiedPost
library:
  source-dirs: src
  pkg-config-dependencies:
    - libsecp256k1
tests:
  spec:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - either
      - hspec
      - hspec-api
      - libsecp256k1
      - monad-par
      - HUnit
